# Start from a base image with g++ and other necessary tools installed
FROM gcc:latest

# Copy your source code into the Docker image
COPY . /app

# Set working directory
WORKDIR /app

# List files in /app and /app/include
RUN ls -l /app && ls -l /app/include

# Compile your program
RUN g++ -o apiServer apiServer.cpp -Iinclude -Wall -Wextra -g3

# Run your program when the container starts
CMD ["./apiServer"]